ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

ARDUINO_LIBS  = RadioHead SPI MCP7940RTC Time Wire 
BOARD_TAG     = atmega328
MONITOR_PORT  = /dev/ttyUSB0

AVR_TOOLS_DIR = /home/jrbenito/arduino-1.0.5/hardware/tools/avr
AVRDUDE       = /usr/share/arduino/hardware/tools/avrdude 
include /home/jrbenito/sketchbook/Arduino-Makefile/Arduino.mk
#include /usr/share/arduino/Arduino.mk
